// Generated by: make types
// Run `make types` after any migration to regenerate this file.

export type Database = {
	public: {
		Tables: {
			profiles: { Row: any; Insert: any; Update: any; Relationships: [] };
			teams: { Row: any; Insert: any; Update: any; Relationships: [] };
			team_members: { Row: any; Insert: any; Update: any; Relationships: [] };
			availabilities: { Row: any; Insert: any; Update: any; Relationships: [] };
			scrims: { Row: any; Insert: any; Update: any; Relationships: [] };
			scrim_teams: { Row: any; Insert: any; Update: any; Relationships: [] };
		};
		Views: Record<string, never>;
		Functions: Record<string, never>;
		Enums: Record<string, never>;
	};
};
